site_name: Jitterbit Style Guide

nav:
-  Welcome: 
    - Welcome to the Jitterbit Style Guide: welcome.md
    - Latest Changes to the Jitterbit Style Guide: changes.md
- A Word about Jitterbit Docs: 
    - A Word about Jitterbit Docs: jdocs.md
- Terms and Usage: 
    - Cloud Studio Terminology: csterms.md
    - Jitterbit Terminology Glossary: glossary.md
    - Avoid Complex Words: avoidcomplexwords.md
- Voice and Tone: 
    - Tone: tone.md
    - Use Plain Language: plainlanguage.md
    - Active Voice: active.md
    - Present Tense: present.md
    - Second Person: second.md
    - Anthropomorphisms: anthro.md
    - Subjunctive Mood: subjunctive.md
- Grammar and Word Choice:
    - Abbreviations: abbrev.md
    - Acronyms: acronym.md
    - Capitalization: caps.md
    - Contractions: contractions.md
    - Example Names and Domains: examples.md
    - Plurals in Parentheses: pluralparen.md
    - Possessives: possessives.md
    - Pronouns: pronouns.md
    - Standard English Spelling and Phrases: standard.md
- Accessibility: 
    - Write for All Users: everyone.md
    - Include alt-text: alt-text.md
- Content Structure: 
    - Document Names, Topic Titles, and Section Headings: doctitlehed.md
    - Writing Procedures: writeproc.md
- Formatting Text: 
#   - Formatting Quick Reference: formattingqr.md
    - Bold  and Italic Type: bold.md
    - Monospaced Text: mono.md
- Images: 
    - Best Practices for Images: imagebest.md
    - Image Types: imagetypes.md
- Links:
    - Best Practices for Links: linksbp.md
    - Link Types: dllinks.md
- Lists: 
    - Best Practices for Lists: listsbp.md
    - Bulleted and Numbered Lists: bnlists.md
- Notes, Tips, Cautions, and Warnings: 
    - Notes, Tips, Cautions, and Warnings: notetipcautionwarning.md
- Numbers: 
    - Numerals or Words?: numorword.md
    - Dates and Time: dates.md
- Symbols and Punctuation: 
    - Ampersand: ampersand.md
    - Apostrophe: apostrophes.md
    - Brackets: brackets.md
    - Colon: colon.md
    - Comma: comma.md
    - Dashes: dashes.md
    - Parentheses: parens.md
    - Percent: percent.md
    - Period: period.md
    - Quotation Marks: quotationmark.md
    - Slashes: slashes.md
    - Special Characters: specialchar.md
- Jitterbit Trademarks:  
    - Trademark Attribution: tm.md
- Tables: 
    - Best Practices for Tables: tablesbp.md
- Third-party Information: 
    - Documenting Third-party and Partner Products: thirdparties.md
- UI Text: 
    - UI Text Style Guidelines: uiguidelines.md
- Additional Resources: 
    - Other Sources: othersources.md

# Uses this script to do tooltips https://github.com/lsaether/md-tooltips
# markdown_extensions:
#     - mdtooltips

#extra_css:
#    - css/tooltips.css

theme: 
  name: readthedocs
  highlightjs: true
  hljs languages:
    - css
    - python
    - yaml
    - javascript
